#!/usr/bin/env bash

sfg_ssh_setup__set_up_ssh_server() {
    local SCRIPT_DIR
    SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>"/dev/null" && pwd)"
    source "${SCRIPT_DIR}/bash_utils/print_utils"

    local START_TEXT="> Setting up SSH server."
    local END_TEXT="< Done setting up SSH server."

    sfg_bash_utils__print_info "${START_TEXT}"
    local conf_filepath="/etc/ssh/sshd_config.d/00-sfg_ssh_server.conf"
    local authorized_keys_dir="/var/cache/sfg/authorized_keys"

    local authorized_keys_command_filepath="/usr/local/bin/sfg_fetch_authorized_keys.py"
    local authorized_keys_command_user="nobody"
    
    # Install the sshd config.
    # shellcheck disable=SC2016
    mkdir -p "$(dirname "${conf_filepath}")"
    AUTHORIZED_KEYS_COMMAND="${authorized_keys_command_filepath} ${authorized_keys_dir}" AUTHORIZED_KEYS_COMMAND_USER="${authorized_keys_command_user}" \
        envsubst '${AUTHORIZED_KEYS_COMMAND} ${AUTHORIZED_KEYS_COMMAND_USER}' <"${SCRIPT_DIR}/../config/ssh_server.conf.template" >"${conf_filepath}"
    chmod 644 "${conf_filepath}"

    # Create the directory that caches the authorized keys.
    mkdir -p "${authorized_keys_dir}"
    chown -R ${authorized_keys_command_user} "${authorized_keys_dir}"
    chmod 700 "${authorized_keys_dir}"

    # Install the fetch_authorized_keys.py script.
    cp "${SCRIPT_DIR}/../scripts/fetch_authorized_keys.py" "${authorized_keys_command_filepath}"
    chown root:root "${authorized_keys_command_filepath}"
    chmod 755 "${authorized_keys_command_filepath}"

    if systemctl is-active --quiet ssh; then
        systemctl restart ssh
    elif systemctl is-active --quiet sshd; then
        systemctl restart sshd
    fi

    sfg_bash_utils__print_info "${END_TEXT}"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    set -e
    source "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>"/dev/null" && pwd)/bash_utils/print_utils"

    if [[ -z "${SUDO_USER}" ]]; then
        sfg_bash_utils__print_error "Invalid invocation: ${*}"
        sfg_bash_utils__print_error "Usage: sudo $0"
        sfg_bash_utils__print_error "Example: sudo $0"
        exit 1
    fi

    sfg_ssh_setup__set_up_ssh_server "${@}"
fi
