#!/usr/bin/env bash

sfg_ssh_setup__set_up_ssh_client() {
    local SCRIPT_DIR
    SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>"/dev/null" && pwd)"
    source "${SCRIPT_DIR}/bash_utils/print_utils"

    local START_TEXT="> Setting up SSH client."
    local END_TEXT="< Done setting up SSH client."

    sfg_bash_utils__print_info "${START_TEXT}"
    local conf_filepath="/etc/ssh/ssh_config.d/00-ssh_client.conf"

    # Install the ssh config.
    mkdir -p "$(dirname "${conf_filepath}")"
    cp "${SCRIPT_DIR}/../config/ssh_client.conf" "${conf_filepath}"
    chmod 644 "${conf_filepath}"
    sfg_bash_utils__print_info "${END_TEXT}"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    set -e
    source "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>"/dev/null" && pwd)/bash_utils/print_utils"

    if [[ -z "${SUDO_USER}" ]]; then
        sfg_bash_utils__print_error "Invalid invocation: ${*}"
        sfg_bash_utils__print_error "Usage: sudo $0"
        sfg_bash_utils__print_error "Example: sudo $0"
        exit 1
    fi

    sfg_ssh_setup__set_up_ssh_client "${@}"
fi
